default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: kaito
  password: root
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: BFF_app_development

test:
  <<: *default
  database: BFF_app_test

production:
  <<: *default
  database: BFF_app_production
  username: root
  password: <%= ENV['BFF_app_DATABASE_PASSWORD'] %>
