default: &default
  adapter: mysql2
  encoding: utf8mb4

  # NOTE: docker-compose
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("DB_USERNAME") { "root" } %>
  password: <%= ENV.fetch("DB_PASSWORD") { "root" } %>
  host: <%= ENV.fetch("DB_HOST") { "db" } %>

  # NOTE: local mysql接続
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # username: kaito
  # password: root
  # socket: /tmp/mysql.sock

development:
  <<: *default
  database: BFF_app_development

test:
  <<: *default
  database: BFF_app_test

production:
  <<: *default
  database: BFF_app_production
  username: root
  password: <%= ENV['BFF_app_DATABASE_PASSWORD'] %>
