version: '3'
services:
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    network_mode: "host"

  localstack:
    image: localstack/localstack
    ports:
      - 8080:8080
      - 4566:4566
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
    volumes:
      - ./docker/localstack/:/docker-entrypoint-initaws.d