version: '3'
services:
  app:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    command: rails s -b '0.0.0.0'
    stdin_open: true
    tty: true
    ports:
      - '13000:3000'
    volumes:
      - .:/app:cached
      - /var/tmp
      - sockets:/app/tmp/sockets
    environment:
      - S3_REGION=ap-northeast-1
      - S3_ACCESS_KEY=dummy
      - S3_SECRET_KEY=dummy
      - S3_BUCKET=posts
      - S3_ENDPOINT=http://localstack:4566
      - S3_ASSET_HOST=http://localhost:4566
    # NOTE: 秘匿情報はenvに書いてあります
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: BFF_app_development
      MYSQL_ROOT_PASSWORD: root
      TZ: "Asia/Tokyo"
    ports:
      - '13306:3306'
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"

  localstack:
    image: localstack/localstack
    ports:
      - 8080:8080
      - 4566:4566
    environment:
      SERVICES: s3
      AWS_DEFAULT_REGION: ap-northeast-1
      DATA_DIR: /tmp/localstack/data
    volumes:
      - ./docker/localstack/:/docker-entrypoint-initaws.d

volumes:
  db_data:
  sockets:
  localstack_data:
